[package]
name = "taos-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = { version = "0.1.56" }
bytes = "1.1.0"
futures = { version = "0.3" }
itertools = "0.10.3"
log = "0.4"
once_cell = "1"
scc = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_repr = "0.1.8"
serde_with = "2.0.0"
taos-error = { path = "../taos-error" }
taos-query = { path = "../taos-query" }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }

[dev-dependencies]
pretty_env_logger = "*"

[features]
default = ["tmq"]
native-tls-vendored = ["tokio-tungstenite/native-tls-vendored"]
sync = []
tmq = []
